export const config = [
  { index: '3', name: 'Willy Renaldi', from: 'English Community' },
  { index: '4', name: 'Hoang Nguyen', from: 'English Community' },
  { index: '5', name: 'Matt Nowack', from: 'English Community' },
  { index: '6', name: 'Sirash', from: 'English Community' },
  { index: '10', name: 'MC', from: 'Italy Community' },
  { index: '12', name: 'Zak', from: 'Italy Community' },
  { index: '13', name: 'Akata', from: 'French Community' },
  { index: '14', name: 'BlackStoneSheperd', from: 'French Community' },
  { index: '16', name: 'Amir', from: 'Persian Community' },
  { index: '19', name: '无题', from: 'Chinese Community' },
  { index: '20', name: '莱斯威特', from: 'Chinese Community' },
  { index: '23', name: '阿龙', from: 'Chinese Community' },
  { index: '24', name: '陈先森', from: 'Chinese Community' },
  { index: '26', name: '别做梦', from: 'Chinese Community' },
  { index: '28', name: '张杨', from: 'Chinese Community' },
  { index: '29', name: 'Cappex', from: 'Italy Community' },
  { index: '30', name: 'Jaime Flores', from: 'Spanish Community' },
  { index: '31', name: 'RHEE', from: 'Korean Community' },
  { index: '32', name: 'Kyle', from: 'Korean Community' },
  { index: '33', name: 'Tioneb', from: 'French Community' },
  { index: '34', name: 'Salih', from: 'German Community' }
]
