export const config = [
  // { index: '1', name: 'Crypto Jedi', from: 'English Community' },
  // { index: '2', name: 'JEKZ', from: 'English Community' },
  { index: '3', name: 'Willy Renaldi', from: 'English Community' },
  { index: '4', name: 'Hoang Nguyen', from: 'English Community' },
  { index: '5', name: 'Matt Nowack', from: 'English Community' },
  { index: '6', name: 'Sirash', from: 'English Community' },
  // { index: '7', name: 'Neon Thunder', from: 'English Community' },
  // { index: '8', name: 'PacoBits', from: 'Spainish Community' },
  // { index: '9', name: 'Lucio', from: 'Spainish Community' },
  { index: '10', name: 'MC', from: 'Italy Community' },
  // { index: '11', name: 'Ondin', from: 'Italy Community' },
  { index: '12', name: 'Zak', from: 'Italy Community' },
  { index: '13', name: 'Akata', from: 'French Community' },
  { index: '14', name: 'BlackStoneSheperd', from: 'French Community' },
  // { index: '15', name: 'James Pham', from: 'Vietnam Community' },
  { index: '16', name: 'Amir', from: 'Persian Community' },
  // { index: '17', name: 'Nova', from: 'Persian Community' },
  // { index: '18', name: '森·焱', from: 'Chinese Community' },
  { index: '19', name: '无题', from: 'Chinese Community' },
  { index: '20', name: '莱斯威特', from: 'Chinese Community' },
  // { index: '21', name: '夕阳', from: 'Chinese Community' },
  // { index: '22', name: 'newsletter', from: 'Chinese Community' },
  { index: '23', name: '阿龙', from: 'Chinese Community' },
  { index: '24', name: '陈先森', from: 'Chinese Community' },
  // { index: '25', name: 't1n6', from: 'Chinese Community' },
  { index: '26', name: '别做梦', from: 'Chinese Community' },
  // { index: '27', name: '来来', from: 'Chinese Community' },
  { index: '28', name: '张杨', from: 'Chinese Community' },
  // { index: '29', name: '海河', from: 'Chinese Community' }
  { index: '30', name: 'Cappex', from: 'Italy Community' },
  { index: '31', name: 'Jaime Flores', from: 'Spanish Community' },
  { index: '32', name: 'RHEE', from: 'Korean Community' },
  { index: '33', name: 'Kyle', from: 'Korean Community' },
  { index: '34', name: 'Tioneb', from: 'French Community' },
  { index: '35', name: 'Salih', from: 'German Community' }
]
